# Generated by Django 5.0.3 on 2024-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('en_promocion', models.BooleanField()),
                ('destacado', models.BooleanField()),
            ],
        ),
    ]
